:jbake-title: Waarom is dit voor mij?
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: Waarom voor mij?
:jbake-order: 3
:filename: \chapters\02_waarom_is_dit_voor_mij.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc: left
:toclevels: 6


[[section-architecture-constraints]]
== Waarom is dit voor mij?
Waarschijnlijk heb je al eens gehoord van termen als de digitale inkomensverklaring, het digitaal delen van gegevens, en de digitale inkomenstoets.

Deze termen verwijzen naar de digitale procedure waarmee woningzoekenden en medebewoners gevalideerde identiteits- en inkomensgegevens delen met de woonruimteverdeler of corporatie via MijnOverheid.

Het is cruciaal dat deze nieuwe digitale procedure zorgvuldig wordt uitgevoerd. Daarom heeft Aedes Datastandaarden de DIV-it-standaard ontwikkeld.

Wil je hier meer over weten? Lees dan verder.

=== De digitale procedure in het kort
Woningcorporaties toetsen verplicht of woningzoekenden een sociale huurwoning mogen huren op basis van het huishoudinkomen. Daarvoor gebruiken corporaties de inkomensgegevens van de woningzoekende en eventuele toekomstige medebewoners. Met de digitale inkomensverklaring kunnen woningzoekenden en medebewoners deze gegevens digitaal delen vanuit overheidsbronnen en kan de woningcorporatie deze gegevens valideren.

====
Om tot een digitale inkomensverklaring te komen, volgen woningzoekenden en medebewoners een digitale procedure waarmee zij gevalideerde identiteits- en inkomensgegevens delen met de woonruimteverdeler of corporatie via MijnOverheid. De digitale inkomensverklaring wordt opgesteld in het woonruimteverdeelsysteem door gegevens uit verschillende bronnen te combineren.
====

De woningcorporatie krijgt met de digitale procedure beschikking over:

* Een BSN, een gevalideerde geslachtsnaam en geboortedatum. Daarmee kan vastgesteld worden dat de persoon voor wie het inkomen digitaal wordt verstrekt, ook de persoon is die al een bepaalde periode ingeschreven staat. (Een afgeleid van) het BSN mag ook alleen hiervoor worden opgeslagen.

* Een gevalideerd inkomensgegeven. Zo kan met zekerheid vastgesteld worden dat het inkomen ook daadwerkelijk bij de woningzoekende hoort, en een betrouwbare bron heeft (Belastingdienst).

Samen worden deze gegevens gebruikt zodat het woonruimteverdeelsysteem een digitale inkomensverklaring kan opstellen, die gebruikt kan worden voor de inkomenstoets.

==== Voordelen van de digitale procedure
Voor woningzoekenden vergemakkelijkt de digitale procedure het toewijzingsproces. Zij kunnen eenvoudig, snel en veilig hun gegevens delen met woningcorporaties. Het is niet langer nodig om allerlei formulieren te downloaden, printen en versturen. Het is niet verplicht om de gegevens digitaal aan te leveren, dus de woningzoekende behoudt de vrijheid om er geen gebruik van te maken en mag te allen tijde de instemming voor het gebruik van de gegevens intrekken. Gedurende de pilot waren woningzoekenden erg positief, unaniem gaven ze de voorkeur aan de nieuwe werkwijze vanwege het gebruiksgemak.

De digitale procedure levert ook de woningcorporatie tijdswinst op: het vermindert de administratieve lasten van woningcorporaties en woonruimteverdelers.

====
*Kostenbesparing*

Uit onderzoek van
https://www.volkshuisvestingnederland.nl/binaries/volkshuisvestingnederland/documenten/rapporten/2022/08/30/eindrapport-regeldruk-wijziging-woningwet-digitale-inkomenstoets/Eindrapport-regeldruk-digitale-inkomenstoets.pdf"[Sira Consulting] 
blijkt dat na aftrek van de kosten die de invoering van de digitale inkomensverklaring met zich mee brengt, de sector jaarlijks zo’n 9.6 miljoen euro kan besparen.
====

En op deze manier ontvangen woningcorporaties betrouwbare gegevens, rechtstreeks van de overheid, waardoor de kans op toewijzingsfraude kleiner wordt. Ook worden de gegevens die de woningzoekende deelt beter beschermd: er worden minder gegevens gedeeld, via een beveiligde verbinding met de overheid.

==== Wat is nodig om de digitale procedure te gaan gebruiken?
Woningcorporaties en woonruimteverdelers moeten een aantal stappen doorlopen voordat zij live kunnen gaan met het digitaal delen van inkomensgegevens. Hierbij gaat het om organisatorische, juridische en technische aanpassingen in de eigen processen en systemen. Zoals proceswijzigingen, afspraken met de accountant, het aanpassen van informatiebeveiligings- en privacydocumentatie en het aansluiten op de digitale infrastructuur van de overheid.

Het is belangrijk dat de uitrol en voorbereiding daarop zorgvuldig gebeuren. Daarom heeft Aedes Datastandaarden de DIV-it-standaard ontwikkeld. Aedes Datastandaarden ondersteunt woningcorporaties, woonruimteverdelers en samenwerkingsverbanden met de DIV-it-standaard bij het implementeren van de digitale procedure. DIV-it schrijft een zorgvuldige en gestandaardiseerde wijze voor om de digitale procedure in gebruik te nemen. Om mogelijke risico’s te mitigeren, adviseren wij om om de digitale inkomensverklaring conform DIV-it te implementeren.


== De DIV-it standaard
DIV-it is de standaard om de digitale procedure zorgvuldig te implementeren. DIV-it is een product van Aedes Datastandaarden. DIV-it 1.2.2 is gepubliceerd op 1 november 2024.

=== Samen kom je verder dan alleen
Alle corporaties en woonruimteverdelers die gebruik willen maken van de identiteits- en inkomensgegevens die via MijnOverheid kunnen worden gedeeld, moeten voldoen aan de eisen die het ministerie stelt.

De DIV-it-standaard gaat verder dan dat. Het heeft voordelen om de DIV-it-standaard te gebruiken, niet alleen individueel maar ook op sectorniveau.

DIV-it is een sectorstandaard. Een sectorstandaard heeft een aantal voordelen. Dankzij interoperabiliteit wordt samenwerken makkelijker en voorkomen we afhankelijkheid van specifieke leveranciers. De positie van corporaties richting overheidspartijen en softwareleveranciers wordt hiermee sterker.

Het schaalvoordeel van het ontwikkelen van een sectorstandaard is dat we meer expertise en kennis bij elkaar brengen en daardoor hogere kwaliteit kunnen leveren. We bouwen een community rond de standaard en dit creëert kansen om elkaar onderling te helpen. Daarnaast bouwen we aan vertrouwen door een gezamenlijk ontwikkelproces en grootschalig gebruik.

Bij het ontwikkelen van de DIV-it-standaard hebben we sterk gelet op zorgvuldigheid richting woningzoekenden en medebewoners, efficiënt gebruik van middelen (tijd en geld), beheersing van risico’s en een duurzame, stabiele implementatie. De onderdelen van de standaard zijn onderling samenhangend.

Gebruik van de DIV-it-standaard is niet verplicht. De DIV-it-standaard is de basis voor de ondersteuning door Aedes. Aedes kan alleen vragen beantwoorden over de inhoud van de standaard, en niet over afwijkende situaties.

=== Versies
DIV-it wordt actief beheerd en doorontwikkeld. Voorgaande versies en wijzigingen zijn te vinden op de pagina DIV-it versiebeheer.

==== Waneeer voldoe ik aan de DIT-it 1.2.2?
Een corporatie of woonruimteverdeler voldoet aan DIV-it 1.2.2 als:

. alle specificaties van het Ministerie van Binnenlandse Zaken en Koninkrijksrelaties worden gevolgd;

.Specificaties van het Ministerie van Binnenlandse Zaken en Koninkrijksrelaties
[%collapsible]
====
Specificaties van het Ministerie van Binnenlandse Zaken en Koninkrijksrelaties

* https://wetten.overheid.nl/jci1.3:c:BWBR0005181&hoofdstuk=IV&afdeling=3&paragraaf=2&artikel=46&z=2024-01-01&g=2024-01-01[Artikel
46 Woningwet] en daarop gebaseerde regelgeving
* https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/documenten/publicaties/2024/01/12/aanvraagformulier-aanvraag-gebruiker[Aanvraagformulier
aanwijzing gebruiker digitalisering inkomensgegevens (versie 15 januari
2024)]
* https://www.logius.nl/domeinen/infrastructuur/diginetwerk/documentatie[Aansluiten
op Diginetwerk (raadpleegdatum 18 juni 2024)]
* Aansluiten koppelvlak Beheervoorziening BSN
** https://www.rvig.nl/aansluitprocedure-bvbsn[Aansluitprocedure BV BSN
(raadpleegdatum 18 juni 2024)]
** https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/documenten/publicaties/2024/01/12/aanvraagformulier-bv-bsn-woonruimteverdeler[Aanvraagformulier
BV BSN Woonruimteverdeler (versie 4 april 2024)]
** https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/documenten/publicaties/2024/01/12/aanvraagformulier-bv-bsn-woningcorporatie[Aanvraagformulier
BV BSN Woningcorporatie (versie 4 april 2024)]
* Aansluiten koppelvlak MijnOverheid en DvmG
** https://www.logius.nl/domeinen/interactie/mijnoverheid/documentatie/voorwaarden-productieomgeving[Aansluitvoorwaarden
MijnOverheid (versie 12 juni 2018)]
** https://www.logius.nl/domeinen/interactie/mijnoverheid/documentatie/api-documentatie-delen-van-mijngegevens[Koppelvlakspecificaties
voor het koppelvlak MijnOverheid en Delen van MijnGegevens
(raadpleegdatum 16 mei 2024)]
** https://www.logius.nl/onze-organisatie/zakendoen-met-logius/voorwaarden/algemene-voorwaarden-logius[Algemene
voorwaarden Logius (versie 12 juni 2018)]
** https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/documenten/publicaties/2024/01/12/formulier-logius-dvmg[Aanvraagformulier
MijnOverheid Delen van MijnGegevens (versie 15 januari 2024)]
* https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/documenten/publicaties/2024/01/12/voorwaarden-voor-gebruik-versie-1.1[Gebruiksvoorwaarden
voor Digitaal delen van het inkomensgegeven (versie 1.1&#44; 28 maart 2024)]
====

[start=2]
. de vier beschreven processen worden aangeboden op de beschreven wijze; daarbij is integratie met andere processen die losstaan van de digitale procedure denkbaar (bijvoorbeeld het vragen van aanvullende gegevens bij de inschrijving), de standaard doet echter geen uitspraken over die andere processen;

. informatie uit Delen van MijnGegevens of de BV BSN niet op een andere manier wordt gebruikt dan in de vier beschreven processen is uitgewerkt: de informatie wordt niet voor andere doelen of in andere processen gebruikt, er wordt geen andere inhoudelijke informatie uit de antwoordberichten verwerkt dan is benoemd, de informatie wordt niet langer bewaard dan nodig voor de uitvoering van of controle op het proces;

. bij uitval binnen een van de beschreven processen de digitale procedure wordt gestaakt, bijvoorbeeld wanneer een van de beschreven uitvalsituaties zich voordoet;

. het BSN alleen in gehashte vorm wordt opgeslagen; verwerking van het zuivere BSN mag alleen plaatsvinden binnen één beschreven proces en wanneer en voor zover dat strikt noodzakelijk is voor de uitvoering van dat beschreven proces; bij uitval binnen een van de beschreven processen wordt het BSN altijd verwijderd;

. de vraag om instemming en de toelichting op de digitale procedure de minimaal vereiste elementen bevat;

. het intrekken van instemming op de beschreven wijze wordt verwerkt;

. met de softwareleverancier is geborgd dat voor livegang een passende ISAE-verklaring een aanwezig is;

. alle maatregelen met betrekking tot de AVG-rolverdeling, privacydocumenten, beveiligingsmaatregelen, bewaartermijnen en de grondslagen zijn ingericht zoals beschreven onder Informatiebeveiliging en privacy;

. een data protection impact assessment (DPIA) is uitgevoerd met behulp van de model-DPIA

Corporaties, woonruimteverdelers en samenwerkingsverbanden kunnen implementatie van een deel van de standaard uitbesteden aan andere partijen (zoals softwareleveranciers) als zij dat doen conform de standaard.


== Wanneer is de DIV-it van toepassing
De DIV-it standaard is ontwikkeld voor een aantal situaties waarin woonruimteverdelers of corporaties de digitale procedure aan mogen bieden.

Als je als woonruimteverdeler of corporatie op eigen verzoek bent aangewezen als gebruiker door het ministerie van BZK, dan moet je de digitale procedure aan iedereen die aan de onderstaande criteria voldoet aanbieden. En je mag het ook alleen aan degenen aanbieden die aan de criteria voldoen.

* *Sociale verhuur*: de digitale procedure mag alleen worden gebruikt voor de uitvoering van de inkomenstoets die is voorgeschreven in de Woningwet en daarmee alleen voor woningzoekenden die sociale huurwoningen willen huren.

* *Uitgezonderde groepen*: het inkomensgegeven mag alleen digitaal gedeeld worden door woningzoekenden die niet in een van de uitgezonderde groepen voor de inkomenstoets vallen en die niet in een van de groepen vallen die uitgezonderd zijn op de verplichte toetsing aan de hand van belastingbescheiden. Zie voor deze groepen: Bijlage 4 Besluit toegelaten instellingen volkshuisvesting 2015.

Daarnaast stelt de wet als voorwaarde dat *instemming* wordt verkregen: de woonruimteverdeler of corporatie moet de woningzoekende en medebewoners verzoeken om in te stemmen met de digitale procedure. Daarbij moet de woonruimteverdeler of corporatie informatie over de procedure en de daarbij behorende gegevensverwerkingen delen met de woningzoekende zodat deze een afgewogen beslissing kan nemen of hij wel of niet zijn gegevens digitaal wil delen. Als de woningzoekende instemt, is de woonruimteverdeler of corporatie verplicht om de digitale procedure toe te passen.

De DIV-it-standaard is ontwikkeld voor de volgende situaties waarin gegevens worden gedeeld:

* Het BSN wordt eenmalig opgevraagd nadat de woningzoekende instemt met de digitale procedure (bij inschrijving of op een later moment, ten behoeve van het verrijken van de inschrijving). Op dat moment vindt ook de validatie van de geslachtsnaam en geboortedatum plaats.

* De combinatie BSN en inkomensgegeven van de woningzoekende en toekomstige medebewoners worden eenmalig opgevraagd nadat de woningzoekende een woning toegewezen heeft gekregen.

De DIV-it-standaard gaat ervan uit dat de woningzoekende ten minste 18 jaar is bij inschrijven.

== Kosten
Er zijn kosten van toepassing op de implementatie en het gebruik van de digitale procedure. Dit zijn kosten voor het gebruik van MijnOverheid en kosten die de softwareleverancier of dienstenleverancier doorbelast.

Aan het gebruik van de voorziening van MijnOverheid zijn kosten verbonden. Meer informatie over deze kosten wordt gedeeld op de pagina https://www.volkshuisvestingnederland.nl/onderwerpen/digitaal-delen-van-inkomensgegevens/aanvraagprocedure-digitaal-delen-inkomensgegevens-voor-woningcorporaties-en-woonruimteverdelers[kosten en randvoorwaarden gebruik voorzieningen]
van het ministerie van BZK. Waarbij het volgende bedoeld wordt met:

* Totaal van aantal DigiD inloggen voor deze toepassing in de sector = elke geslaagde inlogpoging in DigiD door de woningzoekende ongeacht of er vervolgens gegevens worden gedeeld.  

* Totaal aantal geslaagde gegevensdelingen = aantal geslaagde requests, dus daadwerkelijke gegevensdeling.  

Daarnaast kan de softwareleverancier of dienstenleverancier kosten doorberekenen die hij voor de woonruimteverdeler of corporatie maakt voor de implementatie of het gebruik van de digitale inkomensverklaring.

Er zijn geen kosten verbonden aan het gebruik van de Beheervoorziening BSN.



