[[section-context-and-scope]]
== Routekaart
Op de routekaart staan alle belangrijke stappen die jouw organisatie zal nemen om de digitale inkomensverklaring te implementeren.

De implementatie bestaat uit een aantal delen:

. Voorbereiding: Alle stappen die je neemt om je voor te bereiden op de implementatie.

. Het nieuwe proces toepassen: Alle stappen om het nieuwe proces toe te passen.

. Aanmelden bij BZK: Om toegewezen te worden als gebruiker van de digitale inkomensverklaring.

. Aanmelden bij Logius en RvIG: Bij Logius om gebruik te maken van de koppeling “Delen van Mijn Gegevens” en bij de RvIG om gebruik te maken van de Beheervoorziening BSN (BV BSN).

. Livegang, gebruik en beheer: Wanneer ben je klaar voor livegang? En wat volgt daarna?

Daarnaast zijn er een aantal “check-in”-momenten, wanneer het DIV-it-team graag via een formulier van je hoort hoe ver je bent met de implementatie van de digitale inkomensverklaring. Je zal deze check-in momenten vanzelf tegenkomen.

*De routekaart*
[mermaid, width=100%]
...

flowchart LR
subgraph Orienteren
end

AanmeldenAedes["Aanmelden <BR/> bij <BR/> Aedes"]


subgraph Voorbereiden
  direction LR
  Implementatieroute
  Bepalen["Bepalen verwerkings- <br/> verantwoordelijkheid"]
  Advies["Advies <br/> projectteam"]
  Leverancier
end

Orienteren-->AanmeldenAedes
AanmeldenAedes-->Voorbereiden

CP1["Checkpoint"]

Voorbereiden-->CP1

subgraph Toepassen
    direction LR
    NP["Het nieuwe process"]
    AA["Afspraken met de accountant"]
    IP["Informatiebeveiliging en Privacy"]
    DPIA["DPIA"]
    VA["Voorbereiden aanmelding"]
end

CP1-->Toepassen

CP2["Checkpoint"]

Toepassen-->CP2

subgraph Aanmelden
    direction TB
    BZK["Aanmelden bij BZK"]
    CP3["Checkpoint"]
    BZK-->CP3
    LOGIUS["Aanmelden bij Logius"]
    RVIG["Aanmelden bij RvIG"]
    SC["Publicatie in de staatscourant"]
    CP3-->LOGIUS
    CP3-->RVIG
    CP3-->SC
end 

CP2-->Aanmelden

CP4["Checkpoint"]

Aanmelden-->CP4

LIVE["Live gaan <BR/>, gebruik en beheer"]

CP4-->LIVE

Leverancier:::Blue
LOGIUS:::Blue
RVIG:::Blue
Bepalen:::Red
IP:::Red
DPIA:::Red
classDef Blue stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
classDef Red stroke:#b50707, fill:#D50000, color:#FFFFFF


....

<<<
// Voorbereiding
include::03_routekaart_voorbereiding.adoc[]

<<<
// Het nieuwe proces toepassen
include::03_routekaart_toepassen.adoc[]
